### ISSUE TITLE
Dashes in org-mode tables

### ISSUE THREAD

**Issue by krisbalintona** [rnkn/astute#1]
Hi,

Thank you for your package. I use astute in text modes, such as org-mode. But specifically in org-mode, its tables use many hyphens in sequence to denote a horizontal line. Astute renders e.g. each set of 3 hyphens as an em-dash, changing the visuals of the table undesirably.

How would I go about addressing this edge case, and would it be prudent to incorporate those changes (if possible) in astute.el?

**Comment by rnkn** [comment]
Thanks, I'm glad it's useful.

Yes I think I can fix this with some simple regexp. Leave it with me.

**Comment by krisbalintona** [comment]
Hi @rnkn,

I just wanted to follow up on this. I don't mean to rush you since this is a low-priority issue, but I thought I'd follow up in case this had slipped your agenda. I could also start experimenting with a few different regexps and report back any successes if that'd help.

**Comment by rnkn** [comment]
Hi, sorry I made a fix with 1634571b3d6a3640dac637a924d566e16c0ed6e3 but forgot to push it online. Should be in MELPA shortly.

**Comment by krisbalintona** [comment]
Hi,

Thanks for the commmit! I'll be using it over the next few days and will report back if I notice any unexpected edge cases. So far, it seems to work as intended on org tables.

**Comment by krisbalintona** [comment]
Just wanted to follow up. Seems great, so I'll be closing this issue!
